package com.allthingsclaude.battery.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.double
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.time.Instant
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Runs the shared golden fixtures at `fixtures/` against this module.
 *
 * These expectations were transcribed from the Swift suite under
 * `Tests/BatteryTests/` — they are what the Swift implementation asserts, not
 * what this Kotlin produces. That distinction is the whole point: a fixture
 * generated by running the code it checks passes forever and proves nothing.
 * See `fixtures/README.md`.
 *
 * (Note for editors: Kotlin nests block comments, so a literal star-slash
 * sequence like a glob inside this KDoc silently swallows the rest of the file.)
 */
class GoldenFixtureTest {

    private val fixtures: File = System.getProperty("battery.fixtures")
        ?.let(::File)
        ?.takeIf { it.isDirectory }
        ?: fail(
            "Fixture directory not found. It is passed as -Dbattery.fixtures by " +
                "core/build.gradle.kts; running these tests outside Gradle needs it set."
        )

    private fun load(name: String): JsonObject =
        Json.parseToJsonElement(File(fixtures, name).readText()).jsonObject

    // ── UsageLevel ──────────────────────────────────────────────────────────

    @Test
    fun `usage level thresholds match the Swift suite`() {
        val cases = load("usage-level.json")["cases"]!!.jsonArray
        assertTrue(cases.isNotEmpty(), "fixture has no cases")

        for (case in cases) {
            val obj = case.jsonObject
            val utilization = obj["utilization"]!!.jsonPrimitive.double
            val expected = obj["level"]!!.jsonPrimitive.content
            assertEquals(
                expected,
                UsageLevel.from(utilization).name,
                "utilization $utilization (${obj["from"]?.jsonPrimitive?.content})",
            )
        }
    }

    @Test
    fun `palette colours match the Swift suite`() {
        val colors = load("usage-level.json")["colors"]!!.jsonObject
        for (level in UsageLevel.entries) {
            val expected = colors[level.name]?.jsonPrimitive?.content ?: continue
            assertEquals(
                expected.uppercase(),
                "#%08X".format(level.color),
                "colour for ${level.name}",
            )
        }
    }

    // ── TimeFormatting ──────────────────────────────────────────────────────

    @Test
    fun `shortDuration matches the Swift suite`() {
        val cases = load("time-formatting.json")["shortDuration"]!!
            .jsonObject["cases"]!!.jsonArray

        for (case in cases) {
            val obj = case.jsonObject
            val seconds = obj["seconds"]!!.jsonPrimitive.double
            assertEquals(
                obj["expect"]!!.jsonPrimitive.content,
                TimeFormatting.shortDuration(seconds),
                "shortDuration($seconds) ${provenance(obj)}",
            )
        }
    }

    @Test
    fun `relativeTime matches the Swift suite`() {
        val cases = load("time-formatting.json")["relativeTime"]!!
            .jsonObject["cases"]!!.jsonArray

        // A fixed `now` rather than the wall clock: several cases sit exactly on
        // a boundary (59s, 3599s), and letting real time elapse between building
        // the instant and formatting it would flip them intermittently.
        val now = Instant.parse("2026-01-01T12:00:00Z")

        for (case in cases) {
            val obj = case.jsonObject
            val secondsAgo = obj["secondsAgo"]!!.jsonPrimitive.double
            val then = now.minusMillis((secondsAgo * 1000).toLong())
            assertEquals(
                obj["expect"]!!.jsonPrimitive.content,
                TimeFormatting.relativeTime(then, now),
                "relativeTime(${secondsAgo}s ago) ${provenance(obj)}",
            )
        }
    }

    // ── BurnRateCalculator ──────────────────────────────────────────────────

    @Test
    fun `burn rate regression matches the Swift suite`() {
        val cases = load("burn-rate.json")["cases"]!!.jsonArray
        assertTrue(cases.isNotEmpty(), "fixture has no cases")

        for (case in cases) {
            val obj = case.jsonObject
            val name = obj["name"]!!.jsonPrimitive.content

            // `now` is fixed per case so the snapshot offsets, the reset offset
            // and the projection all resolve against one instant. The Swift
            // original calls Date() repeatedly and tolerates the skew with wide
            // ranges; pinning it here makes the same assertions deterministic.
            val now = Instant.parse("2026-01-01T12:00:00Z")
            val caseReset = now.plusSeconds(obj["resetsAtOffsetSeconds"]!!.jsonPrimitive.double.toLong())

            val snapshots = obj["snapshots"]!!.jsonArray.map { element ->
                val s = element.jsonObject
                UsageSnapshot(
                    timestamp = now.minusMillis(
                        (s["minutesAgo"]!!.jsonPrimitive.double * 60_000).toLong()
                    ),
                    sessionUtilization = s["utilization"]!!.jsonPrimitive.double,
                    sessionResetsAt = s["resetsAtOffsetSeconds"]
                        ?.jsonPrimitive?.double
                        ?.let { now.plusSeconds(it.toLong()) }
                        ?: caseReset,
                )
            }

            val result = BurnRateCalculator.calculate(
                snapshots = snapshots,
                currentUtilization = obj["currentUtilization"]!!.jsonPrimitive.double,
                resetsAt = caseReset,
                now = now,
            )

            val expect = obj["expect"]!!.jsonObject

            expect["currentRate"]?.let {
                assertNumber(it.jsonObject, result.currentRate, "$name → currentRate")
            }
            expect["projectedAtReset"]?.let {
                assertNumber(it.jsonObject, result.projectedAtReset, "$name → projectedAtReset")
            }
            expect["trend"]?.let {
                assertEquals(it.jsonPrimitive.content, result.trend.name, "$name → trend")
            }
            expect["hasEnoughData"]?.let {
                assertEquals(it.jsonPrimitive.boolean, result.hasEnoughData, "$name → hasEnoughData")
            }
            expect["projectedLimitTime"]?.jsonObject?.get("isNull")?.let {
                if (it.jsonPrimitive.boolean) {
                    assertNull(result.projectedLimitTime, "$name → projectedLimitTime should be null")
                } else {
                    assertNotNull(result.projectedLimitTime, "$name → projectedLimitTime should be set")
                }
            }
            expect["minutesToLimit"]?.let {
                val limit = assertNotNull(
                    result.projectedLimitTime,
                    "$name → minutesToLimit asserted but no limit projected",
                )
                val minutes = (limit.toEpochMilli() - now.toEpochMilli()) / 60_000.0
                assertNumber(it.jsonObject, minutes, "$name → minutesToLimit")
            }
        }
    }

    @Test
    fun `every burn rate case names the Swift test it came from`() {
        // Guards the property the fixtures exist for. A case with no provenance
        // is a case whose expected values might have been produced by running
        // this Kotlin, which would make it self-confirming.
        val cases = load("burn-rate.json")["cases"]!!.jsonArray
        for (case in cases) {
            val obj = case.jsonObject
            val from = obj["from"]?.jsonPrimitive?.content
            val derived = obj["derived"]?.jsonPrimitive?.content
            assertTrue(
                !from.isNullOrBlank() || !derived.isNullOrBlank(),
                "case '${obj["name"]?.jsonPrimitive?.content}' has neither `from` nor `derived`",
            )
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    /** Applies one expectation object: equals(+accuracy), greaterThan, lessThan, lessThanOrEqual. */
    private fun assertNumber(spec: JsonObject, actual: Double, label: String) {
        spec["equals"]?.jsonPrimitive?.double?.let { expected ->
            val accuracy = spec["accuracy"]?.jsonPrimitive?.doubleOrNull ?: 0.0
            assertTrue(
                abs(actual - expected) <= accuracy,
                "$label: expected $expected ± $accuracy, was $actual",
            )
        }
        spec["greaterThan"]?.jsonPrimitive?.double?.let { bound ->
            assertTrue(actual > bound, "$label: expected > $bound, was $actual")
        }
        spec["lessThan"]?.jsonPrimitive?.double?.let { bound ->
            assertTrue(actual < bound, "$label: expected < $bound, was $actual")
        }
        spec["lessThanOrEqual"]?.jsonPrimitive?.double?.let { bound ->
            assertTrue(actual <= bound, "$label: expected <= $bound, was $actual")
        }
    }

    private fun provenance(obj: JsonObject): String =
        obj["from"]?.jsonPrimitive?.content?.let { "[$it]" }
            ?: obj["derived"]?.jsonPrimitive?.content?.let { "[derived: $it]" }
            ?: ""
}
