#!/bin/bash

# Usage: ./Scripts/release-ios.sh <version|keyword> [--yes]
# Examples:
#   ./Scripts/release-ios.sh 0.2.0
#   ./Scripts/release-ios.sh patch
#   ./Scripts/release-ios.sh minor
#   ./Scripts/release-ios.sh major
#
# The iPhone counterpart to release.sh. Same shape, three differences that
# matter:
#
#   * The version lives in ios/project.yml (MARKETING_VERSION), not Info.plist —
#     the iOS Info.plists are generated by XcodeGen and just reference it.
#   * The tag is `ios-v*`, a separate namespace from the Mac app's `v*`, so a
#     menu-bar release doesn't push a build to TestFlight reviewers.
#   * It asks before pushing. A GitHub release can be deleted; a TestFlight
#     build number is consumed on Apple's side forever and the build goes
#     straight to your testers. Pass --yes to skip the prompt.
#
# There's no Homebrew cask to update — the App Store is the only channel.

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SPEC="ios/project.yml"
ASSUME_YES=false
INPUT=""
DID_COMMIT=false

for arg in "$@"; do
  case "$arg" in
    -y|--yes) ASSUME_YES=true ;;
    *)        INPUT="$arg" ;;
  esac
done

if [ -z "$INPUT" ]; then
  echo "Usage: ./Scripts/release-ios.sh <version|keyword> [--yes]"
  echo ""
  echo "Version: X.Y.Z (e.g., 0.2.0)"
  echo ""
  echo "Keywords:"
  echo "  major  - Bump major version (X.0.0)"
  echo "  minor  - Bump minor version (x.Y.0)"
  echo "  patch  - Bump patch version (x.y.Z)"
  exit 1
fi

# ── Current version ─────────────────────────────────────────────────────
CURRENT_VERSION=$(grep -m1 '^ *MARKETING_VERSION:' "$SPEC" | sed 's/.*"\(.*\)".*/\1/')

if [ -z "$CURRENT_VERSION" ]; then
  echo "Error: Could not read MARKETING_VERSION from $SPEC"
  exit 1
fi

IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

case "$INPUT" in
  major)
    VERSION="$((MAJOR + 1)).0.0"
    echo "Bumping major: $CURRENT_VERSION -> $VERSION"
    ;;
  minor)
    VERSION="$MAJOR.$((MINOR + 1)).0"
    echo "Bumping minor: $CURRENT_VERSION -> $VERSION"
    ;;
  patch)
    VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
    echo "Bumping patch: $CURRENT_VERSION -> $VERSION"
    ;;
  *)
    VERSION="$INPUT"
    if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "Error: Version must be in format X.Y.Z (e.g., 0.2.0) or a keyword (major/minor/patch)"
      exit 1
    fi
    echo "Setting version: $CURRENT_VERSION -> $VERSION"
    ;;
esac

TAG="ios-v$VERSION"

# ── Preflight ───────────────────────────────────────────────────────────
# All of these fail the release workflow ten minutes in. Catching them here
# costs a second.

if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Working tree is dirty. Commit or stash first — the release must"
  echo "       build from exactly what's tagged."
  exit 1
fi

if git rev-parse "$TAG" >/dev/null 2>&1; then
  echo "Error: Tag $TAG already exists."
  echo "       App Store Connect won't accept a build number twice, so bump"
  echo "       the version rather than re-tagging."
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "main" ]; then
  echo "Warning: On branch '$BRANCH', not main."
fi

# The workflow needs all five. A missing one gets discovered after the archive,
# which is the slow part. Only checked when gh is available and logged in.
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  MISSING=""
  EXISTING=$(gh secret list --json name --jq '.[].name' 2>/dev/null || echo "")
  if [ -n "$EXISTING" ]; then
    for required in IOS_CERTIFICATE IOS_CERTIFICATE_PWD \
                    ASC_API_KEY ASC_API_KEY_ID ASC_API_ISSUER_ID; do
      if ! echo "$EXISTING" | grep -qx "$required"; then
        MISSING="$MISSING $required"
      fi
    done
  fi
  if [ -n "$MISSING" ]; then
    echo ""
    echo "Error: Missing repository secrets:$MISSING"
    echo "       See ios/README.md — 'Shipping to TestFlight'."
    exit 1
  fi
fi

echo ""

# ── Bump ────────────────────────────────────────────────────────────────
# CI passes the version from the tag on the xcodebuild command line, so this
# is what a *local* build reports. Keeping it in step means Xcode and
# TestFlight never disagree about what you're looking at.
sed -i '' "s/^\( *MARKETING_VERSION: \)\"[^\"]*\"/\1\"$VERSION\"/" "$SPEC"

NEW_VERSION=$(grep -m1 '^ *MARKETING_VERSION:' "$SPEC" | sed 's/.*"\(.*\)".*/\1/')
if [ "$NEW_VERSION" != "$VERSION" ]; then
  echo "Error: Version bump didn't take — $SPEC still reads '$NEW_VERSION'."
  git checkout -- "$SPEC"
  exit 1
fi

# The spec can already name this version — most obviously on the very first
# release, where the default in project.yml *is* the version being cut. That's
# not an error, there's simply nothing to commit; committing anyway would fail
# and take the whole script down before it ever reaches the tag.
if git diff --quiet -- "$SPEC"; then
  echo "  $SPEC already reads $VERSION — nothing to bump"
else
  echo "  Updated $SPEC to $VERSION"
  git add "$SPEC"
  if ! git commit -q -m "chore(ios): bump version to $VERSION"; then
    echo "Error: Could not commit the version bump."
    git checkout -- "$SPEC"
    exit 1
  fi
  echo "  Committed version bump"
  DID_COMMIT=true
fi

git tag "$TAG"
echo "  Created tag $TAG"

# ── Confirm, then push ──────────────────────────────────────────────────
if [ "$ASSUME_YES" != true ]; then
  echo ""
  echo "About to push $TAG. This uploads a build to TestFlight and releases it"
  echo "to your testers. The build number can't be reused afterwards."
  echo ""
  read -r -p "Push? [y/N] " REPLY
  if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Stopped. $TAG exists locally but nothing was pushed. To undo:"
    # Only offer to rewind HEAD if we actually put a commit there. Suggesting
    # `reset --hard HEAD~1` after a no-op bump would delete somebody's real
    # work — the destructive half of the advice has to be conditional.
    if [ "$DID_COMMIT" = true ]; then
      echo "    git tag -d $TAG && git reset --hard HEAD~1"
    else
      echo "    git tag -d $TAG"
    fi
    exit 0
  fi
fi

git push
git push origin "$TAG"
echo "  Pushed commit and tag to origin"

echo ""
echo "Done! Version bumped to $VERSION"
echo "The iOS release workflow will now build, sign, and upload $TAG to TestFlight."
if command -v gh >/dev/null 2>&1; then
  echo ""
  echo "Follow it with:  gh run watch"
fi
